package com.crx.pojo;

public class Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.id
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.num
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	private String num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.price
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.img
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.miaoshu
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	private String miaoshu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.name
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.id
	 * @return  the value of goods.id
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.id
	 * @param id  the value for goods.id
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.num
	 * @return  the value of goods.num
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public String getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.num
	 * @param num  the value for goods.num
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.price
	 * @return  the value of goods.price
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.price
	 * @param price  the value for goods.price
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.img
	 * @return  the value of goods.img
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.img
	 * @param img  the value for goods.img
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.miaoshu
	 * @return  the value of goods.miaoshu
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public String getMiaoshu() {
		return miaoshu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.miaoshu
	 * @param miaoshu  the value for goods.miaoshu
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public void setMiaoshu(String miaoshu) {
		this.miaoshu = miaoshu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.name
	 * @return  the value of goods.name
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.name
	 * @param name  the value for goods.name
	 * @mbg.generated  Tue Dec 10 22:09:17 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}
}